name: Build iSyncNotif
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.2)'
        required: true
permissions:
  contents: write  # Required for creating releases

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          brew install llvm libplist libxml2 ldid

      - name: Install Theos
        run: |
          git clone --recursive --depth=1 https://github.com/theos/theos.git $HOME/theos

      - name: Download iPhoneOS6.1 SDK
        run: |
          curl -L -o iPhoneOS6.1.sdk.zip https://github.com/growtopiajaw/iPhoneOS-SDK/releases/download/v1.0/iPhoneOS6.1.sdk.zip
          unzip iPhoneOS6.1.sdk.zip -d $HOME/theos/sdks

      - name: Build iSyncNotif
        env:
          THEOS: ${{ env.HOME }}/theos
          SDKVERSION: 6.1
        run: |
          cd ${{ github.workspace }}/iSyncNotif
          make clean
          make

      - name: Upload built binary (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: iSyncNotif
          path: ./iSyncNotif/.theos/obj/debug/iSyncNotif

      - name: Upload to GitHub Release
        if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          name: Release ${{ github.event.inputs.tag || github.ref_name }}
          files: ./iSyncNotif/.theos/obj/debug/iSyncNotif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show example usage script
        run: |
          echo "scp iSyncNotif root@iphone_ip:/usr/bin/"
          echo "ssh root@iphone_ip '/usr/bin/iSyncNotif \"title here\" \"message here\"'"
