name: Build iSyncNotif

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install llvm libplist libxml2

      - name: Install Theos
        run: |
          git clone --recursive --depth=1 https://github.com/theos/theos.git $HOME/theos

      - name: Download iPhoneOS6.1 SDK
        run: |
          curl -L -o iPhoneOS6.1.sdk.zip https://github.com/growtopiajaw/iPhoneOS-SDK/releases/download/v1.0/iPhoneOS6.1.sdk.zip
          unzip iPhoneOS6.1.sdk.zip -d $HOME/theos/sdks

      - name: Build iSyncNotif
        env:
          THEOS: ${{ env.HOME }}/theos
          SDKVERSION: 6.1
        run: |
          cd ${{ github.workspace }}/iSyncNotif
          make clean
          make

      - name: Zip built binary
        run: |
          cd ${{ github.workspace }}/iSyncNotif/obj
          zip isyncnotif.zip isyncnotif

      - name: Upload built zip
        uses: actions/upload-artifact@v4
        with:
          name: isyncnotif
          path: ./iSyncNotif/obj/isyncnotif.zip

      - name: Show example usage script
        run: |
          echo "Example usage:"
          echo "scp isyncnotif.zip root@iphone_ip:/tmp/"
          echo "ssh root@iphone_ip 'unzip /tmp/isyncnotif.zip -d /usr/bin && rm /tmp/isyncnotif.zip'"
          echo "ssh root@iphone_ip '/usr/bin/isyncnotif \"title here\" \"message here\"'"
      - name: build no errors
        run: |
          echo "Pls"
